Amsterdam/amsterdam-styled-components

- packages/asc-core/src/theme/default/index.ts
- packages/asc-core/src/theme/index.ts
- packages/asc-core/src/utils/README.md
- packages/asc-ui/src/theme/index.tsx
> DP-6803 refactored the ThemeFactory to work with theme names

- packages/asc-core/src/components/ContextMenu/ContextMenuButton.ts
- packages/asc-core/src/components/ContextMenu/ContextMenuItem.ts
- packages/asc-ui/src/components/ContextMenu/ContextMenu.tsx
- packages/asc-ui/src/components/ContextMenu/ContextMenuButton.tsx
- packages/asc-ui/src/components/ContextMenu/__tests__/ContextMenu.test.tsx
> Context menu changes

- package.json
- packages/asc-ui/src/components/ContextMenu/ContextMenu.stories.tsx
- packages/asc-ui/src/components/ContextMenu/ContextMenu.tsx
- packages/asc-ui/src/components/ContextMenu/ContextMenuButton.tsx
- packages/asc-ui/src/components/ContextMenu/ContextMenuList.tsx
- packages/asc-ui/src/components/ContextMenu/__tests__/ContextMenu.test.tsx
- packages/asc-ui/src/components/ContextMenu/__tests__/__snapshots__/ContextMenu.test.tsx.snap
> Context menu icon

- .travis.yml
- package.json
> Added verify-integrity script

- config/testing/mocks/svg.ts
- packages/asc-core/src/components/AmsterdamLogoStyle/AmsterdamLogoStyle.ts
- packages/asc-core/src/components/HeaderStyle/HeaderTitleStyle.ts
- packages/asc-ui/src/components/ContextMenu/__tests__/__snapshots__/ContextMenu.test.tsx.snap
- packages/asc-ui/src/components/Header/Header.stories.tsx
- packages/asc-ui/src/components/Header/__tests__/__snapshots__/Header.test.tsx.snap
> fix header style issues

- packages/asc-ui/src/components/Input/InputStyle.ts
- packages/asc-ui/src/components/Input/__snapshots__/Input.test.tsx.snap
- packages/asc-ui/src/components/SearchBar/SearchBar.stories.tsx
- packages/asc-ui/src/components/SearchBar/SearchBar.tsx
- packages/asc-ui/src/components/SearchBar/SearchBarStyle.tsx
- packages/asc-ui/src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
> DP-6844 state moved outside the search bar

- packages/asc-ui/src/components/Header/examples/DataportaalHeader.tsx
- packages/asc-ui/src/components/NewMenu/MenuFlyOut/MenuFlyOutStyle.ts
- packages/asc-ui/src/components/NewMenu/MenuInline/MenuInlineStyle.ts
- packages/asc-ui/src/components/NewMenu/MenuItemLink/MenuItemLinkStyle.ts
- packages/asc-ui/src/components/NewMenu/MenuList/MenuListStyle.ts
- packages/asc-ui/src/components/NewMenu/constants.ts
> Clean up stories, enhanced styling for active menu items

- packages/asc-core/src/theme/default/typography.ts
- packages/asc-ui/src/components/Input/Input.stories.tsx
- packages/asc-ui/src/components/Spinner/Spinner.stories.tsx
- packages/asc-ui/src/components/TextField/TextField.stories.tsx
- packages/asc-ui/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/asc-ui/src/components/TopBar/TopBar.stories.tsx
- packages/asc-ui/src/components/Typography/__snapshots__/Typography.test.tsx.snap
> minor fixes and improvements of the storybook examples

- packages/asc-ui/src/components/Blog/Article/Article.stories.tsx
- packages/asc-ui/src/components/Blog/BlogHeader/BlogHeader.tsx
- packages/asc-ui/src/components/Heading/Heading.test.tsx
- packages/asc-ui/src/components/Heading/__snapshots__/Heading.test.tsx.snap
- packages/asc-ui/src/components/ImageCard/ImageCard.stories.tsx
- packages/asc-ui/src/components/ImageCard/ImageCard.test.tsx
- packages/asc-ui/src/components/ImageCard/__snapshots__/ImageCard.test.tsx.snap
- packages/asc-ui/src/components/Modal/Modal.stories.tsx
- packages/asc-ui/src/internals/ContentFiller/ContentFiller.tsx
> Fixed heading `as` props

- packages/asc-ui/src/components/CardContainer/SpecialCardContainer.stories.tsx
> DP-7020 cards lined up

- packages/asc-ui/src/components/Menu/MenuFlyOut/MenuFlyOut.tsx
> Debounce the menu flyout when it's used as desktop menu

- .eslintignore
- .prettierignore
- CHANGELOG.md
- README.md
- docs/CONTRIBUTING.md
- packages/asc-ui/src/components/Card/examples/CardSpecials.stories.tsx
- packages/asc-ui/src/components/Header/Header.stories.tsx
- packages/asc-ui/src/components/Header/examples/DataportaalHeader.stories.tsx
> DP-7020 minor style improvements in the Special cards

- .travis.yml
- package.json
- yarn.lock
> Removed prettier-eslint, added node version 12, removed 8

- CHANGELOG.md
- packages/asc-ui/src/components/Modal/Modal.tsx
- packages/asc-ui/src/utils/hooks/useTrappedFocus.test.tsx
- packages/asc-ui/src/utils/hooks/useTrappedFocus.ts
> Added useTrappedFocus hook, rewritten Modal to Function Component

- packages/asc-ui/src/components/Focus/Focus.tsx
- packages/asc-ui/src/components/Menu/MenuButton/MenuButtonStyle.ts
- packages/asc-ui/src/components/Menu/MenuToggle/MenuToggle.tsx
- packages/asc-ui/src/components/SearchBarToggle/SearchBarToggle.tsx
> Header tweaks

- packages/asc-ui/src/components/Editorial/EditorialContent/EditorialContentStyle.ts
> Added a 100% width to the editorialcontent component

- CHANGELOG.md
- packages/asc-ui/src/components/Card/examples/CardAboutData.stories.tsx
- packages/asc-ui/src/components/Card/examples/CardArticles.stories.tsx
- packages/asc-ui/src/components/Card/examples/CardGenericFunctions.stories.tsx
- packages/asc-ui/src/components/Card/examples/CardSpecials.stories.tsx
- packages/asc-ui/src/components/Footer/Footer.stories.tsx
- packages/asc-ui/src/components/Footer/Footer.test.tsx
- packages/asc-ui/src/components/Footer/FooterContent/FooterContentStyle.ts
- packages/asc-ui/src/components/Footer/FooterStyle.ts
- packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
- packages/asc-ui/src/components/Link/Link.stories.tsx
- packages/asc-ui/src/components/Link/Link.test.tsx
- packages/asc-ui/src/components/Link/Link.tsx
- packages/asc-ui/src/components/Link/LinkStyle.ts
- packages/asc-ui/src/components/List/List.stories.tsx
- packages/asc-ui/src/components/Modal/Modal.stories.tsx
- tsconfig.json
> Link: added color prop and made linkType deprecated + small changes to Footer-related components

- README.md
- packages/asc-ui/src/components/Header/HeaderWrapperStyle.ts
- packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
> Fixed bug header

- .storybook/webpack.config.js
- package.json
- yarn.lock
> Removed fork-ts-checker-webpack-plugin, now using ATL's CheckerPlugin

- CHANGELOG.md
- packages/asc-ui/src/components/Checkbox/Checkbox.stories.tsx
- packages/asc-ui/src/components/Checkbox/Checkbox.test.tsx
- packages/asc-ui/src/components/Checkbox/Checkbox.tsx
- packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
- packages/asc-ui/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/asc-ui/src/components/Checkbox/index.ts
- packages/asc-ui/src/components/DocumentCover/__snapshots__/DocumentCover.test.tsx.snap
- packages/asc-ui/src/components/Icon/IconStyle.ts
- packages/asc-ui/src/components/Icon/__snapshots__/Icon.test.tsx.snap
- packages/asc-ui/src/components/Label/Label.tsx
- packages/asc-ui/src/components/Label/LabelStyle.ts
- packages/asc-ui/src/components/Label/index.ts
- packages/asc-ui/src/utils/themeUtils.ts
- tsconfig.json
> Added checkbox component

- packages/asc-ui/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/asc-ui/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/asc-ui/src/components/DocumentCover/__snapshots__/DocumentCover.test.tsx.snap
- packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
- packages/asc-ui/src/components/Input/__snapshots__/Input.test.tsx.snap
- packages/asc-ui/src/utils/themeUtils.ts
> focusStyleOutline util: bump specificity and removed z-index

- packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
- packages/asc-ui/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/asc-ui/src/components/Label/LabelStyle.ts
> Applied style fixes for checkbox

- packages/asc-ui/src/components/ImageCard/index.ts
> export the ImageCardWrapperStyle

- packages/asc-ui/src/utils/__tests__/grid.test.ts
- packages/asc-ui/src/utils/grid.ts
> moved the no conflicts value for the grid from max to min

- CHANGELOG.md
- packages/asc-ui/src/components/CustomHTMLBlock/CustomHTMLBlockStyle.ts
- packages/asc-ui/src/components/List/List.stories.tsx
- packages/asc-ui/src/components/List/List.tsx
- packages/asc-ui/src/components/List/ListItemStyle.ts
- packages/asc-ui/src/components/List/ListStyle.ts
- packages/asc-ui/src/components/List/index.ts
- packages/asc-ui/src/index.ts
> Added bullet style to List component

- .github/PULL_REQUEST_TEMPLATE.md
> Updated links in PR template

- packages/asc-core/src/theme/index.ts
- packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
- packages/asc-ui/src/components/Heading/__snapshots__/Heading.test.tsx.snap
- packages/asc-ui/src/components/ImageCard/__snapshots__/ImageCard.test.tsx.snap
- packages/asc-ui/src/components/Paragraph/__snapshots__/Paragraph.test.tsx.snap
- packages/asc-ui/src/utils/__tests__/__snapshots__/themeUtils.test.ts.snap
- packages/asc-ui/src/utils/themeUtils.ts
> fixed the color and improved typing in the typography styles

- lerna.json
- packages/asc-core/package.json
- packages/asc-ui/package.json
> Bugfix set color

- packages/asc-ui/src/components/Button/ButtonStyle.ts
- packages/asc-ui/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/asc-ui/src/components/Card/CardStyle.ts
- packages/asc-ui/src/components/DocumentCover/__snapshots__/DocumentCover.test.tsx.snap
- packages/asc-ui/src/components/ImageCard/ImageCardStyle.ts
- packages/asc-ui/src/utils/themeUtils.ts
> Loading animation state

- packages/asc-ui/src/utils/__tests__/themeUtils.test.ts
- packages/asc-ui/src/utils/themeUtils.ts
> Wrapped theme utils fn's in styled-component's css method

- CHANGELOG.md
- packages/asc-core/src/theme/default/typography.ts
- packages/asc-ui/src/components/Editorial/Article/Article.stories.tsx
- packages/asc-ui/src/components/Heading/__snapshots__/Heading.test.tsx.snap
- packages/asc-ui/src/components/ImageCard/__snapshots__/ImageCard.test.tsx.snap
- packages/asc-ui/src/components/Paragraph/Paragraph.stories.tsx
- packages/asc-ui/src/components/Paragraph/Paragraph.tsx
- packages/asc-ui/src/components/Paragraph/ParagraphStyle.ts
- packages/asc-ui/src/components/Paragraph/__snapshots__/Paragraph.test.tsx.snap
- packages/asc-ui/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/asc-ui/src/components/Typography/Typography.tsx
- packages/asc-ui/src/components/Typography/TypographyStyle.ts
- packages/asc-ui/src/utils/__tests__/themeUtils.test.ts
> remove dataportaal specific implementation of the paragraph

- CHANGELOG.md
- packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
- packages/asc-ui/src/theme/CompactThemeProvider.tsx
> Compact theme breakpoints

- packages/asc-ui/src/components/CustomHTMLBlock/CustomHTMLBlockStyle.ts
> Use the inline link style for custom html blocks

- packages/asc-ui/src/theme/CompactThemeProvider.tsx
> Added breakpoints to the compact theme

- CHANGELOG.md
- packages/asc-ui/src/components/Checkbox/Checkbox.stories.tsx
- packages/asc-ui/src/components/Checkbox/Checkbox.tsx
- packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
- packages/asc-ui/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/asc-ui/src/components/Checkbox/index.ts
- packages/asc-ui/src/components/Label/LabelStyle.ts
- Added: Checkbox has Error state, by passing an `error` prop
- Added: default `position` prop for Label(Text) is 'right'
- Fixed: updated Checkbox according to design system
> Minor fixes and changes on Checkbox and Label

- README.md
I thought this might come in handy for a quick start...
> Add npm install line for convenience

- CHANGELOG.md
- packages/asc-ui/src/components/Checkbox/Checkbox.stories.tsx
- packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
- packages/asc-ui/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
> Checkbox tertiary variant

- README.md
> Document package linking example.

- packages/asc-ui/src/components/FilterOption/FilterOption.tsx
- packages/asc-ui/src/components/FilterOption/FilterOptionStyle.ts
> Modified styles in FilterOptions

- CHANGELOG.md
- packages/asc-ui/src/components/Button/ToggleButton/ToggleButtonStyle.ts
> Keep the same background colour as per Nico request.

- CHANGELOG.md
- packages/asc-ui/src/components/Button/Button.stories.tsx
- packages/asc-ui/src/components/Button/ButtonStyle.ts
- packages/asc-ui/src/components/deprecated/IconButton/__snapshots__/IconButton.test.tsx.snap
> Text Button variant update: no padding and auto height

- CHANGELOG.md
- packages/asc-ui/src/components/Button/Button.tsx
- packages/asc-ui/src/components/Menu/Menu.stories.tsx
- packages/asc-ui/src/components/Menu/MenuButton/MenuButton.tsx
- packages/asc-ui/src/components/Menu/MenuButton/MenuButtonStyle.ts
> Added active prop to MenuButton to enable activeStyles

- docs/CONTRIBUTING.md
> Minor update on contributing documentation

- CHANGELOG.md
- packages/asc-ui/src/components/BackDrop/BackDrop.tsx
- packages/asc-ui/src/components/BackDrop/BackDropStyle.ts
- packages/asc-ui/src/components/BackDrop/index.ts
- packages/asc-ui/src/components/Button/ToggleButton/ToggleButton.tsx
- packages/asc-ui/src/components/Header/HeaderWrapperStyle.ts
- packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
- packages/asc-ui/src/components/Menu/Menu.stories.tsx
- packages/asc-ui/src/components/Menu/MenuInline/MenuInline.tsx
- packages/asc-ui/src/components/Menu/MenuInline/MenuInlineStyle.ts
- packages/asc-ui/src/components/Menu/MenuToggle/MenuToggle.tsx
- packages/asc-ui/src/components/Menu/MenuToggle/MenuToggleStyle.ts
- packages/asc-ui/src/components/Menu/constants.ts
- packages/asc-ui/src/components/Modal/Modal.tsx
- packages/asc-ui/src/components/Modal/ModalStyle.ts
- packages/asc-ui/src/components/Portal/Portal.tsx
- packages/asc-ui/src/components/SearchBar/SearchBar.stories.tsx
- packages/asc-ui/src/components/SearchBarToggle/SearchBarToggle.stories.tsx
- packages/asc-ui/src/components/SearchBarToggle/SearchBarToggleStyle.ts
- packages/asc-ui/src/components/Toggle/Toggle.tsx
- packages/asc-ui/src/components/Toggle/ToggleStyle.ts
- packages/asc-ui/src/components/shared/constants.ts
- packages/asc-ui/src/index.ts
- packages/asc-ui/src/utils/__tests__/themeUtils.test.ts
- packages/asc-ui/src/utils/index.ts
- packages/asc-ui/src/utils/themeUtils.ts
> Backdrop component

- packages/asc-ui/src/components/Portal/Portal.tsx
- packages/asc-ui/src/utils/themeUtils.ts
> Portal bugfix

- packages/asc-assets/package.json
- packages/asc-core/package.json
- packages/asc-ui/package.json
- packages/asc-ui/src/components/GlobalStyle/GlobalStyle.test.tsx
- tsconfig.json
> Build to es6 instead of es5 to decrease build size and improve IDE hints

- packages/asc-ui/src/components/Radio/Radio.tsx
> Destructed useEffect

- CHANGELOG.md
- packages/asc-ui/src/components/FilterBox/FilterBox.stories.tsx
- packages/asc-ui/src/components/FilterBox/FilterBox.test.tsx
- packages/asc-ui/src/components/FilterBox/FilterBox.tsx
- packages/asc-ui/src/components/FilterBox/FilterBoxStyle.ts
> Simplified FilterBox component

- CHANGELOG.md
- packages/asc-core/src/theme/index.ts
- packages/asc-ui/src/components/Select/Select.stories.tsx
- packages/asc-ui/src/components/Select/Select.test.tsx
- packages/asc-ui/src/components/Select/Select.tsx
- packages/asc-ui/src/components/Select/SelectStyle.ts
- packages/asc-ui/src/components/Select/__snapshots__/Select.test.tsx.snap
- packages/asc-ui/src/components/Select/index.ts
- packages/asc-ui/src/index.ts
- yarn.lock
> Added Select (Dropdown) component

- CHANGELOG.md
> Updated changelog for canary release

- packages/asc-ui/src/components/FormLabelStyle/FormLabelStyle.ts
- packages/asc-ui/src/components/TextField/TextField.stories.tsx
> Minor update on FormLabel styling

- CHANGELOG.md
- packages/asc-assets/package.json
- packages/asc-core/package.json
- packages/asc-ui/package.json
- packages/asc-ui/src/components/SearchBar/SearchBar.tsx
- packages/asc-ui/src/components/ViewerContainer/ViewerContainer.tsx
- packages/asc-ui/src/components/ViewerContainer/ViewerContainerStyle.ts
- packages/asc-ui/src/index.ts
- tsconfig.json
> ViewerContainer component

- CHANGELOG.md
- packages/asc-ui/src/components/BackDrop/BackDrop.tsx
- packages/asc-ui/src/components/Focus/Focus.tsx
- packages/asc-ui/src/components/Modal/Modal.tsx
- packages/asc-ui/src/components/Modal/ModalStyle.ts
> Fixed modal issue: closing modal when clicking on it

- CHANGELOG.md
- packages/asc-ui/src/components/BackDrop/BackDropStyle.ts
- packages/asc-ui/src/components/Modal/Modal.tsx
- packages/asc-ui/src/components/Modal/ModalStyle.ts
- packages/asc-ui/src/utils/themeUtils.ts
>  Make it possible to pass a z-index offset to the backdrop

- CHANGELOG.md
- packages/asc-ui/src/index.ts
- packages/asc-ui/src/utils/themeUtils.ts
> Export perceivedLoading so it can be used in other apps

- .gitignore
- jest.config.js
- package.json
- packages/asc-assets/package.json
- packages/asc-assets/tsconfig.es.json
- packages/asc-core/package.json
- packages/asc-core/tsconfig.es.json
- packages/asc-ui/package.json
- packages/asc-ui/tsconfig.es.json
> Support ES2015 modules!

- .eslintrc.js
- packages/asc-ui/src/components/Select/Select.test.tsx
- packages/asc-ui/src/components/Select/Select.tsx
Another step towards closing https://github.com/Amsterdam/amsterdam-styled-components/issues/218
> Add a forwardRef to the Select component

- packages/asc-ui/src/components/Checkbox/Checkbox.test.tsx
- packages/asc-ui/src/components/Checkbox/Checkbox.tsx
- packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
This PR:
- adds ref to Checkbox component
- includes unit test
> Add a forwardRef to the Checkbox component

- packages/asc-ui/src/components/Radio/Radio.test.tsx
- packages/asc-ui/src/components/Radio/Radio.tsx
In this PR:
- added ref to radio 
- added unit tests
> Add a forwardRef to the Radio component

- CHANGELOG.md
- packages/asc-core/src/index.ts
- packages/asc-ui/src/components/Button/Button.tsx
- packages/asc-ui/src/components/Card/Card.stories.tsx
- packages/asc-ui/src/components/DocumentCover/DocumentCover.tsx
- packages/asc-ui/src/components/Editorial/EditorialHeader/EditorialHeader.tsx
- packages/asc-ui/src/components/FilterBox/FilterBox.tsx
- packages/asc-ui/src/components/FilterTag/FilterTag.tsx
- packages/asc-ui/src/components/Footer/Footer.stories.tsx
- packages/asc-ui/src/components/Footer/FooterHeading/FooterHeading.tsx
- packages/asc-ui/src/components/Footer/FooterToggle/ToggleFooterHeader.tsx
- packages/asc-ui/src/components/Heading/Heading.stories.tsx
- packages/asc-ui/src/components/Heading/Heading.test.tsx
- packages/asc-ui/src/components/Heading/Heading.tsx
- packages/asc-ui/src/components/Heading/HeadingStyle.ts
- packages/asc-ui/src/components/ImageCard/ImageCard.stories.tsx
- packages/asc-ui/src/components/ImageCard/ImageCard.test.tsx
- packages/asc-ui/src/components/Link/Link.tsx
- packages/asc-ui/src/components/Menu/Menu.stories.tsx
- packages/asc-ui/src/components/Menu/MenuButton/MenuButtonStyle.ts
- packages/asc-ui/src/components/Menu/MenuFlyOut/MenuFlyOut.test.tsx
- packages/asc-ui/src/components/Menu/MenuItemTitle/MenuItemTitle.test.tsx
- packages/asc-ui/src/components/Menu/MenuItemTitle/MenuItemTitle.tsx
- packages/asc-ui/src/components/Modal/Modal.stories.tsx
- packages/asc-ui/src/components/Tag/Tag.tsx
- packages/asc-ui/src/components/Typography/Typography.tsx
- packages/asc-ui/src/components/Typography/TypographyStyle.ts
> Replaced $as with forwardedAs

- CHANGELOG.md
- packages/asc-ui/src/components/Alert/Alert.stories.tsx
- packages/asc-ui/src/components/Alert/Alert.test.tsx
- packages/asc-ui/src/components/Alert/Alert.tsx
- packages/asc-ui/src/components/Alert/AlertStyle.ts
- packages/asc-ui/src/components/Alert/index.ts
- packages/asc-ui/src/components/Button/Button.stories.tsx
- packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
- packages/asc-ui/src/components/Link/LinkStyle.ts
- packages/asc-ui/src/index.ts
https://deploy-preview-286--amsterdam-styled-components.netlify.com/?path=/story/composed-infocard--variants
> Added Alert component

- package.json
- packages/asc-ui/src/components/Alert/Alert.stories.tsx
- packages/asc-ui/src/components/Blockquote/Blockquote.tsx
- packages/asc-ui/src/components/Card/Card.stories.tsx
- packages/asc-ui/src/components/FilterTag/FilterTagStyle.ts
- packages/asc-ui/src/components/Heading/Heading.test.tsx
- packages/asc-ui/src/components/Heading/Heading.tsx
- packages/asc-ui/src/components/Link/Link.tsx
- packages/asc-ui/src/components/Menu/MenuButton/MenuButton.tsx
- packages/asc-ui/src/components/Paragraph/Paragraph.tsx
- packages/asc-ui/src/components/Tag/Tag.tsx
> Forward as prop to extended components

- packages/asc-ui/src/components/Input/Input.test.tsx
- packages/asc-ui/src/components/Input/Input.tsx
In this PR:
- added ref to Input component
- added test
> Add a forwardRef to the Input component

- CHANGELOG.md
- packages/asc-ui/src/components/Accordion/Accordion.stories.tsx
- packages/asc-ui/src/components/Accordion/Accordion.test.tsx
- packages/asc-ui/src/components/Accordion/Accordion.tsx
- packages/asc-ui/src/components/Accordion/AccordionStyle.ts
- packages/asc-ui/src/components/Accordion/AccordionWrapper.tsx
- packages/asc-ui/src/components/Accordion/README.md
- packages/asc-ui/src/components/Accordion/index.ts
- packages/asc-ui/src/components/Button/ButtonStyle.ts
- packages/asc-ui/src/components/ContextMenu/ContextMenu.test.tsx
- packages/asc-ui/src/components/Menu/MenuFlyOut/MenuFlyOut.test.tsx
- packages/asc-ui/src/components/Toggle/Toggle.test.tsx
- packages/asc-ui/src/components/Toggle/Toggle.tsx
- packages/asc-ui/src/components/deprecated/IconButton/__snapshots__/IconButton.test.tsx.snap
- packages/asc-ui/src/index.ts
- packages/asc-ui/src/types/KeyboardKeys.ts
- packages/asc-ui/src/utils/hooks/useFocusWithArrows.tsx
- packages/asc-ui/src/utils/hooks/useOptionalControlledState.ts
- packages/asc-ui/src/utils/themeUtils.ts
> Added Accordion Component

- CHANGELOG.md
- packages/asc-ui/src/components/AmsterdamLogo/AmsterdamLogo.tsx
- packages/asc-ui/src/components/AmsterdamLogo/AmsterdamLogoStyle.ts
- packages/asc-ui/src/components/Button/ShareButton/ShareButton.tsx
- packages/asc-ui/src/components/FormLabelStyle/FormLabelStyle.ts
- packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
- packages/asc-ui/src/components/Select/Select.tsx
- packages/asc-ui/src/components/Select/SelectStyle.ts
- packages/asc-ui/src/components/Select/__snapshots__/Select.test.tsx.snap
- packages/asc-ui/src/components/TextField/TextField.tsx
- packages/asc-ui/src/components/TextField/TextFieldStyle.ts
Reverts Amsterdam/amsterdam-styled-components#356
> Revert "Added improvements to the input, button and link components after acc…"

- CHANGELOG.md
- packages/asc-assets/package.json
- packages/asc-core/package.json
- packages/asc-ui/package.json
- yarn.lock
> Updated deps + SC is now a peerDependency

- CHANGELOG.md
- packages/asc-assets/static/icons/Indeterminate.svg
- packages/asc-ui/src/components/Checkbox/Checkbox.stories.tsx
- packages/asc-ui/src/components/Checkbox/Checkbox.tsx
- packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
> Added indeterminate state to Checkbox

- packages/asc-ui/src/components/List/List.stories.tsx
- packages/asc-ui/src/components/List/OrderedListStyle.ts
Fixes: https://github.com/Amsterdam/amsterdam-styled-components/issues/215
> Updated OrderedList component, added nested story

- packages/asc-assets/package.json
- yarn.lock
> Moved asc-assets dependencies to devDependencies

- CHANGELOG.md
- packages/asc-ui/src/components/Accordion/Accordion.tsx
- packages/asc-ui/src/components/BackDrop/BackDrop.tsx
- packages/asc-ui/src/components/Header/Header.stories.tsx
- packages/asc-ui/src/components/Header/Header.tsx
- packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
- packages/asc-ui/src/components/Label/Label.tsx
> Updated CHANGELOG.md, added AmsterdamLogo as defaultProp in Header

- CHANGELOG.md
- packages/asc-ui/src/components/Hidden/Hidden.stories.tsx
- packages/asc-ui/src/components/Hidden/Hidden.test.tsx
- packages/asc-ui/src/components/Hidden/Hidden.tsx
- packages/asc-ui/src/components/Hidden/README.md
- packages/asc-ui/src/components/Hidden/index.ts
- packages/asc-ui/src/index.ts
- packages/asc-ui/src/utils/hooks/index.ts
- packages/asc-ui/src/utils/hooks/useMatchMedia.ts
> Added Responsive component

- packages/asc-ui/src/utils/hooks/useMatchMedia.ts
> Add support for safari / ios for useMatchMedia hook

- CHANGELOG.md
- packages/asc-ui/src/components/TopTaskButton/README.md
- packages/asc-ui/src/components/TopTaskButton/TopDownButton.test.tsx
- packages/asc-ui/src/components/TopTaskButton/TopTaskButton.stories.tsx
- packages/asc-ui/src/components/TopTaskButton/TopTaskButton.tsx
- packages/asc-ui/src/components/TopTaskButton/TopTaskButtonStyle.ts
- packages/asc-ui/src/components/TopTaskButton/index.ts
- packages/asc-ui/src/index.ts
- yarn.lock
In this PR:
- added top task button
> Add the TopTaskButton component

- CHANGELOG.md
- examples/create-react-app/src/index.css
- packages/asc-ui/src/components/FormTitle/FormTitle.stories.tsx
- packages/asc-ui/src/components/FormTitle/FormTitle.test.tsx
- packages/asc-ui/src/components/FormTitle/FormTitle.tsx
- packages/asc-ui/src/components/FormTitle/FormTitleStyle.ts
- packages/asc-ui/src/components/FormTitle/README.md
- packages/asc-ui/src/components/FormTitle/index.ts
- packages/asc-ui/src/components/GlobalStyle/GlobalStyle.ts
- packages/asc-ui/src/index.ts
- yarn.lock
> Feat: Added FormTitle component

- packages/asc-ui/src/components/Checkbox/Checkbox.stories.tsx
- packages/asc-ui/src/components/Checkbox/README.md
- packages/asc-ui/src/components/Input/Input.stories.tsx
- packages/asc-ui/src/components/Input/README.md
- packages/asc-ui/src/components/Radio/README.md
- packages/asc-ui/src/components/Radio/Radio.stories.tsx
- packages/asc-ui/src/components/Select/README.md
- packages/asc-ui/src/components/Select/Select.stories.tsx
> Add examples of using refs on form elements

- CHANGELOG.md
- packages/asc-ui/src/components/Alert/index.ts
- packages/asc-ui/src/index.ts
> Fix: renamed AlertMessage to Alert

- CHANGELOG.md
- packages/asc-ui/src/components/Input/Input.tsx
- packages/asc-ui/src/components/Input/InputStyle.ts
- packages/asc-ui/src/components/Input/index.ts
- packages/asc-ui/src/components/TextArea/README.md
- packages/asc-ui/src/components/TextArea/TextArea.stories.tsx
- packages/asc-ui/src/components/TextArea/TextArea.test.tsx
- packages/asc-ui/src/components/TextArea/TextArea.tsx
- packages/asc-ui/src/components/TextArea/TextAreaStyle.ts
- packages/asc-ui/src/components/TextArea/index.ts
- packages/asc-ui/src/components/TextField/TextField.tsx
- packages/asc-ui/src/index.ts
I added a TextArea component following the designsystem.
https://designsystem.amsterdam.nl/7awj1hc9f/p/939dd9-text-area
> Added TextArea component

- packages/asc-ui/src/components/TopTaskButton/TopDownButton.test.tsx
- packages/asc-ui/src/components/TopTaskButton/TopTaskButton.stories.tsx
- packages/asc-ui/src/components/TopTaskButton/TopTaskButton.tsx
- packages/asc-ui/src/components/TopTaskButton/TopTaskButtonStyle.ts
Adds the missing variant of the TopTaskButton with a description.
> Add text variant of TopTaskButton

- CHANGELOG.md
- packages/asc-ui/src/components/ErrorMessage/ErrorMessage.stories.tsx
- packages/asc-ui/src/components/ErrorMessage/ErrorMessage.test.tsx
- packages/asc-ui/src/components/ErrorMessage/ErrorMessage.tsx
- packages/asc-ui/src/components/ErrorMessage/ErrorMessageStyle.ts
- packages/asc-ui/src/components/ErrorMessage/README.md
- packages/asc-ui/src/components/ErrorMessage/index.ts
- packages/asc-ui/src/index.ts
- yarn.lock
Added ErrorMessage component
Used this spec: https://designsystem.amsterdam.nl/7awj1hc9f/p/35e7b1-error-message
> Implement ErrorMessage component

- packages/asc-ui/src/components/Accordion/Accordion.stories.mdx
- packages/asc-ui/src/components/Accordion/README.md
> Moved description from Accordion's README.md to mdx file

- CHANGELOG.md
- packages/asc-ui/src/components/Icon/Icon.stories.tsx
- packages/asc-ui/src/components/Icon/Icon.test.tsx
- packages/asc-ui/src/components/Icon/IconStyle.ts
in the Icon component refactored color prop to be string
> Icon color prop now string

- packages/asc-assets/package.json
- packages/asc-ui/package.json
Re-enables support for ESM modules. Will be merged after issues have been resolved.
> Re-enable support for ESM modules

- .storybook/main.js
- .storybook/tsconfig.json
- package.json
- yarn.lock
> Fixed storybook build issue

- README.md
- packages/asc-assets/README.md
- packages/asc-ui/README.md
> Update docs with 'Getting started' section and add fonts guide

- .storybook/main.js
I got Storybook working for IE11 (localhost and build) (-:
#628
> Updated storybook webpack to work in IE11

- packages/asc-ui/src/components/Menu/MenuInline/MenuInline.tsx
- packages/asc-ui/src/components/Toggle/Toggle.tsx
> Add all backdrop props to the components with a backdrop

- packages/asc-ui/src/components/Select/Select.stories.mdx
- packages/asc-ui/src/components/Select/SelectStyle.ts
- packages/asc-ui/src/utils/themeUtils.ts
> Fix selectbox

- packages/asc-ui/src/components/Footer/FooterSectionStyle.ts
> Minor styling fix on Button in FooterSection

- _templates/component/new/style.ejs.t
- _templates/component/new/tsx.ejs.t
- packages/asc-ui/src/components/ShowMoreShowLess/ShowMoreShowLess.test.tsx
- packages/asc-ui/src/components/ShowMoreShowLess/ShowMoreShowLess.tsx
- packages/asc-ui/src/components/ShowMoreShowLess/ShowMoreShowLessStyle.ts
- packages/asc-ui/src/components/ShowMoreShowLess/index.ts
- packages/asc-ui/src/index.ts
- stories/src/ui/ShowMoreShowLess.stories.mdx
- yarn.lock
> Added ShowMoreShowLess component

- packages/asc-ui/src/components/Menu/MenuFlyOut/MenuFlyOut.test.tsx
- packages/asc-ui/src/components/Menu/MenuFlyOut/MenuFlyOut.tsx
> WCAG: close MenuFlyOut on escape

- packages/asc-ui/src/utils/themeUtils.ts
> Change to correct value

- packages/asc-ui/src/components/Menu/MenuFlyOut/MenuFlyOut.test.tsx
- packages/asc-ui/src/components/Menu/MenuFlyOut/MenuFlyOut.tsx
> Add close on escape for hover as well

- .stylelintrc
- CHANGELOG.md
- examples/create-react-app/src/App.jsx
- packages/asc-ui/src/components/Link/Link.test.tsx
- packages/asc-ui/src/components/Link/Link.tsx
- packages/asc-ui/src/components/Link/LinkStyle.ts
- stories/src/ui/Footer.stories.mdx
- stories/src/ui/Link.stories.mdx
> Refactored Link component

- packages/asc-ui/package.json
- packages/asc-ui/src/components/Link/LinkStyle.ts
> Using em svg distance

- packages/asc-ui/src/components/ShowMoreShowLess/ShowMoreShowLessStyle.ts
> Added gradientBackground prop to ShowMoreShowLess component

- CHANGELOG.md
- packages/asc-ui/src/components/Tabs/Tab.tsx
- packages/asc-ui/src/components/Tabs/TabButton.tsx
- packages/asc-ui/src/components/Tabs/TabList.tsx
- packages/asc-ui/src/components/Tabs/Tabs.test.tsx
- packages/asc-ui/src/components/Tabs/Tabs.tsx
- packages/asc-ui/src/components/Tabs/index.ts
- packages/asc-ui/src/index.ts
- packages/asc-ui/src/types/KeyboardKeys.ts
- packages/asc-ui/src/utils/hooks/useFocusWithArrows.tsx
- stories/src/ui/Tabs.stories.mdx
- yarn.lock
See the reference from the Design System: https://designsystem.amsterdam.nl/7awj1hc9f/p/15737c-tab-navigation
> Add Tabs component

- packages/asc-ui/src/components/Tabs/TabButton.tsx
> Fixed bug with inset box-shadow on TabButton

- CHANGELOG.md
- packages/asc-ui/src/components/Tabs/TabList.tsx
> Tabs align fade

- CHANGELOG.md
- packages/asc-ui/src/components/Tabs/TabButton.tsx
- stories/src/ui/Tabs.stories.mdx
> Implement Tabs feedback

- CHANGELOG.md
- packages/asc-ui/src/components/Button/ButtonStyle.ts
> Taskflow button had a styling issue when focussed

- CHANGELOG.md
- packages/asc-ui/src/components/Alert/AlertStyle.ts
> Fixed min-width on Alert close button

- CHANGELOG.md
- packages/asc-ui/src/components/Tabs/Tabs.test.tsx
- packages/asc-ui/src/components/Tabs/Tabs.tsx
- stories/src/ui/Tabs.stories.mdx
> Added `initialTabIndex` prop to Tabs component

- CHANGELOG.md
- packages/asc-ui/src/components/SearchBar/SearchBarStyle.ts
> fixed elongated button in searchbar component

- CHANGELOG.md
- packages/asc-ui/src/components/Breadcrumbs/BreadcrumbsStyle.tsx
Change in line-height makes the design according to design-system spec. See https://designsystem.amsterdam.nl/7awj1hc9f/p/35ca97-breadcrumbs/t/3373
> Change line-height

- CHANGELOG.md
- packages/asc-ui/src/components/Checkbox/Checkbox.test.tsx
- packages/asc-ui/src/components/Checkbox/Checkbox.tsx
- packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
- stories/src/ui/Checkbox.stories.mdx
removed all variants of Checkbox component
> Remove all variants of checkbox component

- stories/src/ui/TextArea.stories.mdx
very small PR 1 change: moved TextArea component from Typography to Form
> moved TextArea component from Typography to Form

- package.json
> added amsterdam/asc-assets v0.29.3 to package because of errors in MSC

- CHANGELOG.md
- packages/asc-ui/src/components/ContextMenu/ContextMenu.tsx
- packages/asc-ui/src/components/Link/LinkStyle.ts
- [x ] You've added or updated the README.mdx of the story of the component
- [x ] You have been following the guidelines, written in the [README](../blob/main/docs/CONTRIBUTING.md#user-content-conventions-and-rules) file
- [ x] Your code has the necessary tests written
- [x ] You've exported the component in [index.ts](./packages/asc-ui/src/index.ts)
- [x ] You have updated the [CHANGELOG.md unreleased sections](../blob/main/CHANGELOG.md#muser-content-unreleased)
> Fixed small issues to prevent unnecessary warnings when rendering components 

- CHANGELOG.md
- packages/asc-ui/src/components/Footer/FooterSection.tsx
- packages/asc-ui/src/components/Footer/FooterSectionStyle.ts
- stories/src/ui/Footer.stories.mdx
> Footer ssr

- CHANGELOG.md
- packages/asc-ui/src/components/TextField/TextField.tsx
- packages/asc-ui/src/components/TextField/TextFieldStyle.ts
- stories/src/ui/TextField.stories.mdx
> Fixed close button style issues in `TextField` component

- CHANGELOG.md
- packages/asc-ui/src/components/Link/LinkStyle.ts
> Fixed: `Link` icons are now aligned properly based on line-height

- CHANGELOG.md
- packages/asc-ui/src/components/Pagination/Pagination.test.tsx
- packages/asc-ui/src/components/Pagination/Pagination.tsx
https://github.com/Amsterdam/amsterdam-styled-components/issues/1922#issue-1094468554
#1922
> Pagination - page prop can be managed externally

- packages/asc-ui/src/components/StepByStepNav/StepByStepNavStyle.ts
Fixes a couple of issues concerning alignment as well as active element background color.
> Fix alignment in StepByStepNav component

- packages/asc-ui/src/components/StepByStepNav/StepByStepNav.test.tsx
- packages/asc-ui/src/components/StepByStepNav/StepByStepNav.tsx
- packages/asc-ui/src/components/StepByStepNav/StepByStepNavStyle.ts
- stories/src/ui/StepByStepNav.stories.mdx
Exposes the `breakpoint` prop on the component and accepts a mediaquery string.
> Custom breakpoint in StepByStepNav component

- examples/nextjs/.babelrc
- examples/nextjs/README.md
- examples/nextjs/next.config.js
- examples/nextjs/package.json
- examples/nextjs/scripts/copy-fonts.sh
> Fix nextjs example

- CHANGELOG.md
- packages/asc-ui/src/components/Modal/Modal.test.tsx
- packages/asc-ui/src/components/Modal/Modal.tsx
Hi,
Took a stab at issue 2246. If any changes are needed, please let me know :slightly_smiling_face: 
Fixes #2246
> pass Modal prop zIndexOffset also to BackDrop

- CHANGELOG.md
- packages/asc-ui/src/components/StepByStepNav/StepByStepNav.tsx
- packages/asc-ui/src/components/StepByStepNav/StepByStepNavStyle.ts
- stories/src/ui/StepByStepNav.stories.mdx
Added the option to add a component to StepByStepNav. So that I create make a subList within the StepByStepNav
> Added component option to StepByStepNav
