Amsterdam/amsterdam-styled-components

jest.config.js
packages/asc-core/src/utils/README.md
packages/asc-core/src/utils/__tests__/fromTheme.test.ts
packages/asc-core/src/utils/fromTheme.ts
packages/asc-core/src/utils/index.ts

This PR:
- adds a utility function for theme configuration value retrieval (`fromTheme`) that can be used inside a styled component,
- adds an index file for the `asc-core/src/utils` folder

(Chore) fromTheme utility functions

---

packages/asc-core/src/components/ButtonBaseStyle/ButtonBaseStyle.ts
packages/asc-core/src/components/ButtonStyle/ButtonStyle.ts
packages/asc-core/src/components/ContextMenu/ContextMenuButton.ts
packages/asc-core/src/components/ContextMenu/ContextMenuItem.ts
packages/asc-core/src/components/ContextMenu/ContextMenuList.ts
packages/asc-core/src/components/GlobalStyle/GlobalStyle.ts
packages/asc-core/src/components/HeaderStyle/HeaderMenuStyle.ts
packages/asc-core/src/components/HeaderStyle/HeaderSearchStyle.ts
packages/asc-core/src/components/HeaderStyle/HeaderStyle.ts
packages/asc-core/src/components/HeaderStyle/HeaderTitleStyle.ts
packages/asc-core/src/components/IconStyle/IconStyle.ts
packages/asc-core/src/components/ShareButtonStyle/ShareButtonStyle.ts
packages/asc-core/src/components/Typography/Typography.ts
packages/asc-core/src/utils/README.md
packages/asc-core/src/utils/__tests__/themeUtils.test.ts
packages/asc-core/src/utils/index.ts
packages/asc-core/src/utils/themeUtils.ts

Theme selectors improvements

---

packages/asc-core/src/utils/themeUtils.ts

Readable color can't handle the Amsterdam red

---

_templates/component/new/stories.ejs.t
packages/asc-core/src/theme/default/typography.ts
packages/asc-ui/src/components/CustomHTMLBlock/CustomHTMLBlockStyle.ts
packages/asc-ui/src/components/DocumentCover/__snapshots__/DocumentCover.test.tsx.snap
packages/asc-ui/src/components/Grid/Container.tsx
packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
packages/asc-ui/src/components/Heading/Heading.tsx
packages/asc-ui/src/components/Heading/HeadingStyle.ts
packages/asc-ui/src/components/Heading/__snapshots__/Heading.test.tsx.snap
packages/asc-ui/src/components/ImageCard/ImageCard.stories.tsx
packages/asc-ui/src/components/ImageCard/ImageCard.test.tsx
packages/asc-ui/src/components/ImageCard/ImageCard.tsx
packages/asc-ui/src/components/ImageCard/ImageCardContent/ImageCardContent.tsx
packages/asc-ui/src/components/ImageCard/ImageCardContent/ImageCardContentStyle.ts
packages/asc-ui/src/components/ImageCard/ImageCardContent/index.ts
packages/asc-ui/src/components/ImageCard/ImageCardStyle.ts
packages/asc-ui/src/components/ImageCard/__snapshots__/ImageCard.test.tsx.snap
packages/asc-ui/src/components/ImageCard/index.ts
packages/asc-ui/src/components/Link/__snapshots__/Link.test.tsx.snap
packages/asc-ui/src/components/Paragraph/ParagraphStyle.ts
packages/asc-ui/src/components/Paragraph/__snapshots__/Paragraph.test.tsx.snap
packages/asc-ui/src/components/TextField/__snapshots__/TextField.test.tsx.snap
packages/asc-ui/src/components/Typography/TypographyStyle.ts
packages/asc-ui/src/index.ts
packages/asc-ui/src/utils/themeUtils.ts

Added ImageCard components, moved 'strong' prop to typography

---

packages/asc-ui/src/components/DocumentCover/__snapshots__/DocumentCover.test.tsx.snap
packages/asc-ui/src/components/Footer/FooterHeading/FooterToggle.tsx
packages/asc-ui/src/components/Footer/FooterHeading/ToggleFooterHeader.tsx
packages/asc-ui/src/components/Header/HeaderStyle.ts
packages/asc-ui/src/components/Header/HeaderWrapperStyle.ts
packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap
packages/asc-ui/src/components/IconButton/IconButtonStyle.ts
packages/asc-ui/src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
packages/asc-ui/src/components/Toggle/Toggle.test.tsx
packages/asc-ui/src/components/Toggle/Toggle.tsx
packages/asc-ui/src/components/Toggle/ToggleHandlerButton.tsx
packages/asc-ui/src/components/Toggle/index.ts
packages/asc-ui/src/utils/themeUtils.ts

Renamed ToggleHeader -> ToggleHandler, fixed svg fill and header issues

---

CHANGELOG.md
packages/asc-ui/src/components/Button/Button.stories.tsx
packages/asc-ui/src/components/Button/ButtonStyle.ts
packages/asc-ui/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/asc-ui/src/components/DocumentCover/__snapshots__/DocumentCover.test.tsx.snap
packages/asc-ui/src/components/deprecated/IconButton/__snapshots__/IconButton.test.tsx.snap

1. Height of all buttons is 46px instead of 44px (See design system: 
> De hoogte van knoppen is altijd 44 px.
2. If buttons parent container height has a fixed height (eg: 100px) then the buttons height is automatically increasing its size:
3. Set `z-index: 0` to fix bug on `:focus`

Fixed button size

---

packages/asc-ui/src/components/Button/ButtonStyle.ts

- Added `font-weight: 700` to `textButton` variant
See [Design System](https://designsystem.amsterdam.nl/7awj1hc9f/p/25ff19/i/848318)

Added `font-weight: 700` to `textButton` variant

---

.storybook/webpack.config.js
CHANGELOG.md

Try to open [amsterdam-styled-components](https://amsterdam.github.io/amsterdam-styled-components/?path=/story/atoms-typography-blockquote--default-style) in IE11 and you get this:
I added `babel-loader` to webpack and it solves the problem.
Now it looks normal:
_The other changes are by Netlify..._

Added storybook support for ie11

---

CHANGELOG.md
packages/asc-ui/src/components/FormLabelStyle/FormLabelStyle.ts
packages/asc-ui/src/components/Input/Input.tsx
packages/asc-ui/src/components/Input/InputStyle.ts
packages/asc-ui/src/components/TextField/TextField.stories.tsx
packages/asc-ui/src/components/TextField/TextField.tsx

- Changed: TextField got new `FormLabel` with `errorMessage`
- Changed: FormLabel has updated style (to design system)
- Changed: Input has `error` variant
Check these Storybook pages:
- https://5df1fcaf6e23b20009cc5b75--amsterdam-styled-components.netlify.com/?path=/story/atoms-textfield--default-state
- https://5df1fcaf6e23b20009cc5b75--amsterdam-styled-components.netlify.com/?path=/story/atoms-textfield--default-state-with-label-and-error

Changed: Input has error state; FormLabel updated style;  FormLabel got error messages

---

packages/asc-ui/src/components/Input/InputStyle.ts
packages/asc-ui/src/components/Input/__snapshots__/Input.test.tsx.snap

This PR removes attributes that were hardcoded on the `Input` component. These attributes prevented setting the `type` attribute of the HTMLElement, for instance.

(chore) Remove hardcoded input attributes

---

CHANGELOG.md
packages/asc-ui/src/components/Menu/MenuToggle/MenuToggle.tsx
packages/asc-ui/src/components/Menu/MenuToggle/MenuToggleStyle.ts
packages/asc-ui/src/components/Modal/ModalStyle.ts
packages/asc-ui/src/utils/hooks/useOptionalControlledState.test.tsx
packages/asc-ui/src/utils/hooks/useOptionalControlledState.ts

Fixed: click outside modal box didn't close the modal, added: "open" prop to MenuToggle to also control the open-state outside of the component

---

CHANGELOG.md
packages/asc-ui/src/components/CompactPager/CompactPager.stories.tsx
packages/asc-ui/src/components/CompactPager/CompactPager.test.tsx
packages/asc-ui/src/components/CompactPager/CompactPager.tsx
packages/asc-ui/src/components/CompactPager/CompactPagerStyle.ts
packages/asc-ui/src/components/CompactPager/index.ts
packages/asc-ui/src/components/CompactPager/test-ids.ts
packages/asc-ui/src/index.ts

This PR adds a new CompactPager component which allows the user to create a pager for a collection of a set number of items and divide them into a specified number of pages.

Add CompactPager component

---

CHANGELOG.md
packages/asc-ui/src/components/Header/HeaderTitleStyle.ts
packages/asc-ui/src/components/Header/__snapshots__/Header.test.tsx.snap

Removed: `text-decoration` hover styling from the `HeaderTitle` component

---

CHANGELOG.md
packages/asc-ui/src/components/Checkbox/Checkbox.tsx
packages/asc-ui/src/components/Radio/Radio.tsx
yarn.lock

Since [React 16.13.0](https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render) there has been an update on some warnings:
>  It is supported to call setState during render, but only for the same component. If you call setState during a render on a different component, you will now see a warning:
> ```Warning: Cannot update a component from inside the function body of a different component.```
> This warning will help you find application bugs caused by unintentional state changes. In the rare case that you intentionally want to change the state of another component as a result of rendering, you can wrap the setState call into useEffect.

Fixed: Radio and Checkbox warnings on new setState() updates by react-dom.

---

CHANGELOG.md
packages/asc-ui/src/components/Alert/Alert.stories.mdx
packages/asc-ui/src/components/Alert/Alert.tsx
packages/asc-ui/src/components/Alert/AlertStyle.ts

- removed `compact` prop/variant for Alert
- updated the styling conform to design system
- updated `AlertStyle` to make component easier customisable 
- IE11 fix: display 'flex' only when dismissible

Fix: removed the compact prop/variant in Alert

---

CHANGELOG.md
packages/asc-ui/src/components/GlobalStyle/GlobalStyle.ts
packages/asc-ui/src/components/Menu/MenuList/MenuListStyle.ts
packages/asc-ui/src/components/Select/Select.stories.mdx
packages/asc-ui/src/components/Select/Select.tsx
packages/asc-ui/src/components/Select/SelectStyle.ts

This PR adds the capability of long texts in the Select component. When the text is too long, the overflow will be shown with ellipsis.
Closes #614

Handle large text overflow in Select component

---

CHANGELOG.md
packages/asc-ui/src/components/Button/ButtonStyle.ts
packages/asc-ui/src/components/ContextMenu/ContextMenu.tsx
packages/asc-ui/src/components/FilterBox/FilterBox.tsx
packages/asc-ui/src/components/Menu/MenuFlyOut/MenuFlyOut.test.tsx
packages/asc-ui/src/components/SearchBar/SearchBar.tsx
packages/asc-ui/src/components/Typography/Typography.tsx
packages/asc-ui/src/components/Typography/TypographyStyle.ts
packages/asc-ui/src/types/Theme.ts
packages/asc-ui/src/utils/deprecatedWarning.ts
packages/asc-ui/src/utils/index.ts

- Added a general deprecated console warning avoided by lint
- Deprecated the `color` prop in `Typography`
- Fixed test warnings from `MenuFlyOut/MenuFlyOut.test.tsx`

Added deprecatedWarning + Deprecated the color prop in Typography + Paragraph

---

docs/GETTING_STARTED.md

Without the starting `/` it is a relative link and links to a page that does not exist (`/docs/packages/asc-assets/README.md#Fonts`).

Fix link to fonts documentation

---

CHANGELOG.md
packages/asc-ui/src/components/Checkbox/Checkbox.test.tsx
packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
packages/asc-ui/src/components/Radio/RadioStyle.ts

The Checkbox and Radio had a transparent background:
And now they're white:

Radio and Checkbox now have a white background

---

packages/asc-ui/src/components/Label/Label.tsx

This PR adds a bit more flexibility to the label component. There are cases where an icon needs to be placed before the text label, or text labels need finegrained multiline/colored design.
```
const title = <><Icon/> Some label</>;
<Label htmlFor={item.id} label={title}>
<Checkbox />
</Label>
const title = <><span>Some label</span><sup>&copy;</sup></>;
<Label htmlFor={item.id} label={title}>
<Checkbox />
</Label>
const title = <><span>Some label</span><button onClick={readDisclaimer}>disclaimer</button></>;
<Label htmlFor={item.id} label={title}>
<Checkbox />
</Label>
```

Allow React components for customized label markup

---

CHANGELOG.md
packages/asc-ui/src/components/FormTitle/FormTitle.test.tsx
packages/asc-ui/src/components/FormTitle/FormTitleStyle.ts
stories/src/ui/FormTitle.stories.mdx

Better to set in your project by giving the wrapper a max-width

Removed style rule max-width from FormTitle

---

packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts

Fixes a bug where the checkbox cannot be toggled if it does not have a label.

Ignore pointer events on Checkbox icon

---

CHANGELOG.md
packages/asc-ui/src/components/Button/ButtonStyle.ts

According to the [design system](https://designsystem.amsterdam.nl/7awj1hc9f/p/25ff19-buttons/t/a148) the Buttons should be at least 90px width. In my project I'm having a bug with a Button with very small text. This should fix it.
I'm only applying this on primary, secondary and tertiary variants.
NB: prettier is really annoying by automatically changing files that causes eslint to fail 😠

Buttons need to be at least 90px width

---

CHANGELOG.md
packages/asc-ui/src/components/Radio/RadioStyle.ts

The problem with the active state was that it was missing a `z-index`. After adding this, it's working again.
#1165

Radio button active state had bug on IE11

---

packages/asc-ui/src/components/Focus/Focus.tsx

When triggering the Modal, React ~~gives~~ gave a warning about a `zIndexOffset` prop that is not recognised.
See #1289

Fixed the Modal component `zIndexOffset` prop warning 

---

CHANGELOG.md
packages/asc-ui/src/components/Button/ButtonStyle.ts

As discussed with DST I’ve updated some Buttons focus state. The focus state on the `primary`, `secondary` and `tertiary` Buttons now have the same background-color as the hover. This makes the Button more striking for users that don't have a custom focus outline or focus color.
---
Old primary unfocussed:
Old primary focussed:
New primary focussed:
---
Old tertiary unfocussed:
Old tertiary focussed:
New tertiary focussed:

Added background color to the Button focus state

---

CHANGELOG.md
packages/asc-ui/src/components/Alert/Alert.tsx
packages/asc-ui/src/components/Alert/AlertStyle.ts
stories/src/ui/Alert.stories.mdx

I created four levels (colors) and the option to set the color as outline (instead of the background)
Result:
Related issue: #1245 
Related Trello card: https://trello.com/c/VyP5R53K/348-alerts-kleur-voorstel

Updated variants/levels for Alert component

---

CHANGELOG.md
packages/asc-ui/src/components/Select/Select.tsx
packages/asc-ui/src/components/Select/SelectStyle.ts
packages/asc-ui/src/components/Select/index.ts
packages/asc-ui/src/index.ts
yarn.lock

This PR:
- shows the default browser focus style in the select component
- exports the `SelectContentWrapperStyle` to ease the customization 
- sets the `className` on the `SelectWrapper` so the component can be properly styled

Show default browser focus style in the select component

---

CHANGELOG.md
packages/asc-ui/src/components/Button/Button.tsx
packages/asc-ui/src/components/Header/Header.tsx
packages/asc-ui/src/components/Header/HeaderContent.tsx
packages/asc-ui/src/components/Header/HeaderLinks.tsx
packages/asc-ui/src/components/Header/HeaderLogoText.tsx
packages/asc-ui/src/components/Header/HeaderTitle.tsx
packages/asc-ui/src/components/Toggle/Toggle.tsx
stories/src/ui/Header.stories.mdx

Added `headerLogoTextAs` prop to `Header` component to overwrite the default `h1` tag

---

packages/asc-ui/src/components/Button/ButtonStyle.ts

I did some tests with the latest canary release in my own project. I found two bugs in Safari that I tried to solve in my previous PR #1548. Safari 10 had an issue with the line-height and Safari 14 still has same issue with the focus.
O/t: I think it's not easy to browser-test asc-ui in Storybook in the localhost setup. I would be really nice if Netlify builds each PR. But that's a different topic.. 
Safari 10 bug:
Safari 10 bug solved:
Safari 14 bug (still remains):
I tried a lot to solve the Safari 14 bug, but unfortunately it remains.

Fixed taskflow button bug for Safari 10

---

packages/asc-ui/src/components/TextField/TextFieldStyle.ts

A simple fix for the alignment of the clear button in search inputs since it overlapped with the focus outline.
Before:
After:

Fixed clear button alignment for (search) inputs

---

packages/asc-ui/src/components/Breadcrumbs/BreadcrumbsStyle.tsx
stories/src/ui/Breadcrumbs.stories.mdx

- Remove padding-inline-start spacing from ordered list
- Also style span children. This makes it possible to also add items that are not anchor links (like the current page).

Styling Breadcrumbs

---

CHANGELOG.md
packages/asc-ui/src/components/Checkbox/Checkbox.test.tsx
packages/asc-ui/src/components/Checkbox/Checkbox.tsx
packages/asc-ui/src/components/Checkbox/CheckboxStyle.ts
packages/asc-ui/src/components/Radio/RadioStyle.ts

When using a `<Checkbox />` or `<Radio />` component, we have to wrap the component with a label to make sure that both the label and the input are clickable.
``` 
// Radio.stories.mdx
<RadioGroup name="group">
<Label htmlFor="radio-1" label="Default">
<Radio id="radio-1" />
</Label>
<Label htmlFor="radio-2" label="Checked">
<Radio id="radio-2" checked />
</Label>
</RadioGroup>
```
However, this means that labels contain a `div` tag (In `<Radio />`), which is invalid HTML: `div` is not part of the [content model](https://html.spec.whatwg.org/multipage/forms.html#the-label-element) of a label. This PR changes it to a `span`

Change radio/checkbox components wrapper tag

---

CHANGELOG.md
packages/asc-ui/src/components/Table/Table.tsx
stories/src/ui/Table.stories.mdx

Fixed: default 100% width for `Table` component
